admins: [1919745140] 

forwards:
  - source: -1001713025945
    dest: [-1001607112940,-1001544025276,-1001235542789]

plugins:
  filter:
    text:
      "RUN BANAKAR OUT": Run Banakar Out
      "CATCH OUTâœ”ï¸âœ”ï¸": ğŸš¾ CATCH OUT ğŸš¾
      "WIDE âœ”ï¸âœ”ï¸" : ğŸ¾ WIDE ğŸ¾
      "RUN OUTâœ”ï¸âœ”ï¸": ğŸš¾ RUN OUT ğŸš¾
      "âœ”ï¸âœ”ï¸": " "
